Add base code

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,36 +1,35 @@
 version: 2.1
 
-orbs:
-  slack: circleci/slack@4.0.2
-
-### It's a good practice to keep your commands at the top of the config file. In this project, you'll need at least 2 commands:
-
 commands:
-#   destroy-environment:
-#     description: Destroy backend and frontend cloudformation stacks given a workflow ID.
-#     ...
-
-#   revert-migration:
-#     description: Revert the last migration if successfully run in the current workflow.
-#     ...
-  create-env-file:
-    description: CREATE env file
-    steps:
-      - run:
-          name: Add env variables
-          command: |
-            echo "NODE_ENV=production" >> backend/.env
-            echo "VERSION=1" >> backend/.env
-            echo "TYPEORM_CONNECTION=${TYPEORM_CONNECTION}" >> backend/.env
-            echo "TYPEORM_MIGRATIONS_DIR=${TYPEORM_MIGRATIONS_DIR}" >> backend/.env
-            echo "TYPEORM_ENTITIES=${TYPEORM_ENTITIES}" >> backend/.env
-            echo "TYPEORM_MIGRATIONS=${TYPEORM_MIGRATIONS}" >> backend/.env
-            echo "TYPEORM_HOST=${TYPEORM_HOST}" >> backend/.env
-            echo "TYPEORM_PORT=${TYPEORM_PORT}" >> backend/.env
-            echo "TYPEORM_USERNAME=${TYPEORM_USERNAME}" >> backend/.env
-            echo "TYPEORM_PASSWORD=${TYPEORM_PASSWORD}" >> backend/.env
-            echo "TYPEORM_DATABASE=${TYPEORM_DATABASE}" >> backend/.env
-            cat backend/.env
+  # destroy-environment:
+  #   description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
+  #   parameters:
+  #     # Add parameter here   
+  #   steps:
+  #     - run:
+  #         name: Destroy environments
+  #         when: on_fail
+  #         command: |
+  #           # Your code here
+  #           exit 1
+  # revert-migrations:
+  #   description: Revert the last migration if successfully run in the current workflow.
+  #   parameters:
+  #     # Add parameter here     
+  #   steps:
+  #     - run:
+  #         name: Revert migrations
+  #         # Add when this will run
+  #         command: |
+  #           # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
+  #           SUCCESS = 1
+  #           if(( $SUCCESS==1 )); 
+  #           then
+  #           #  cd ~/project/backend
+  #           #  npm install
+  #           #  Add revert code here. You can find this in the Getting Started section.
+  #             exit 1
+  #           fi
 
 jobs:
 #  build-frontend:
@@ -39,36 +38,44 @@ jobs:
       - image: circleci/node:13.8.0
     steps:
       - checkout
+      - restore_cache:
+          keys: [frontend-build]
       - run:
           name: BUILD frontend
           command: |
             cd frontend
             npm i
             npm run build
-      - slack/notify:
-          event: fail
-          template: basic_fail_1
+      - save_cache:
+          paths: [frontend/node_modules]
+          key: frontend-build
+
 #  build-backend:
   buildBackEnd:
     docker:
       - image: circleci/node:13.8.0
     steps:
       - checkout
+      - restore_cache:
+          keys: [backend-build]
       - run:
           name: BUILD backend 
           command: |
             cd backend
             npm i
             npm run build
-      - slack/notify:
-          event: fail
-          template: basic_fail_1 
+      - save_cache:
+          paths: [backend/node_modules]
+          key: backend-build
+
 #  test-frontend:
   testFrontEnd:
     docker:
       - image: circleci/node:13.8.0
     steps:
-      - checkout     
+      - checkout
+      - restore_cache:
+          keys: [frontend-build] 
       - run:
           name: TEST frontend
           command: |
@@ -76,46 +83,65 @@ jobs:
             npm i
             npm install oauth-sign
             npm run test
-      - store_test_results:
-          path: frontend
+      - save_cache:
+          paths: [frontend/node_modules]
+          key: frontend-build
+
 #  test-backend:
   testBackEnd:
     docker:
       - image: circleci/node:13.8.0
     steps:
       - checkout
+      - restore_cache:
+          keys: [backend-build]
       - run:
           name: TEST backend
           command: |
             cd backend
             npm i
-            npm run test   
+            npm run test
+      - save_cache:
+          paths: [backend/node_modules]
+          key: backend-build
       - store_test_results:
           path: backend
+
 #  scan-frontend:
   auditFrontEnd:
     docker:
       - image: circleci/node:13.8.0
     steps:
       - checkout
+      - restore_cache:
+          keys: [frontend-build]
       - run:
           name: AUDIT frontend
           command: |
             cd frontend
             npm i
             npm audit fix --audit-level=critical --force
+      - save_cache:
+          paths: [frontend/node_modules]
+          key: frontend-build
+
 #  scan-backend:
   auditBackEnd:
     docker:
       - image: circleci/node:13.8.0
     steps:
       - checkout
+      - restore_cache:
+          keys: [backend-build]
       - run:
           name: AUDIT backend
           command: |
             cd backend
             npm i
             npm audit fix --audit-level=critical --force
+      - save_cache:
+          paths: [backend/node_modules]
+          key: backend-build
 
 #  deploy-infrastructure:
   deploy-infrastructure:
@@ -146,7 +172,6 @@ jobs:
       - run:
           name: ADD EC2 INSTANCE to ansible inventory
           command: |
-            echo "[all]" > .circleci/ansible/inventory.txt
             aws ec2 describe-instances \
               --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
               --query 'Reservations[*].Instances[*].PublicIpAddress' \
@@ -156,6 +181,8 @@ jobs:
             root: ~/
             paths:
                 - "project/.circleci/ansible/inventory.txt"
+      # Here's where you will add some code to rollback on failure
+
 #  configure-infrastructure:
   configure-infrastructure:
     docker:
@@ -170,19 +197,19 @@ jobs:
           name: Install dependencies
           command: |
             apk add --update ansible
-      - create-env-file
       - run:
           name: CONFIGURE server
           command: |
             cd .circleci/ansible
             ansible-playbook -i inventory.txt configure-server.yml
+      # Here's where you will add some code to rollback on failure
+
 #  run-migrations:
   run-migrations:
     docker:
       - image: circleci/node:13.8.0
     steps:
       - checkout
-      - create-env-file
       - run:
           name: MIGRATIONS
           command: |
@@ -195,6 +222,7 @@ jobs:
             curl -H "Content-Type: text/plain" -H "token: ${CIRCLE_WORKFLOW_ID:0:7}"  --request PUT \
               --data $( grep -c "has been executed successfully" migrations.txt ) \
               https://api.memstash.io/values/migration_completion
+      # Here's where you will add some code to rollback on failure
 
 #  deploy-frontend:
   deploy-frontend:
@@ -230,6 +258,8 @@ jobs:
           name: COPY BUILD frontend to the S3 bucket
           command: |
             aws s3 cp ./frontend/dist s3://udapeople-"${CIRCLE_WORKFLOW_ID:0:7}" --recursive
+    # Here's where you will add some code to rollback on failure
+
 #  deploy-backend:  
   deploy-backend:
     docker:
@@ -244,12 +274,13 @@ jobs:
           name: Install dependencies
           command: |
             apk add --update ansible
-      - create-env-file
       - run:
           name: Configure server
           command: |
             cd .circleci/ansible
             ansible-playbook -i inventory.txt deploy.yml
+    # Here's where you will add some code to rollback on failure
+
 #  smoke-test:
   smoke-test:
     docker:
@@ -284,39 +315,47 @@ jobs:
             fi
 
 #  cloudfront-update:
+  # cloudfront-update:
+  #   docker:
+  #     - image: amazon/aws-cli
+  #   steps:
+  #     - checkout
+  #     - run:
+  #         name: Install dependencies
+  #         command: |
+  #           # your code here
+  #     - run:
+  #         name: Update cloudfront distribution
+  #         command: |
+  #           # your code here
+      # Here's where you will add some code to rollback on failure  
 
 workflows:
   default:
     jobs:
-      # - buildFrontEnd
-      # - buildBackEnd
-      # - testFrontEnd:
-      #     requires:
-      #       - buildFrontEnd
-      # - testBackEnd:
-      #     requires:
-      #       - buildBackEnd
-      # - auditFrontEnd:
-      #     requires:
-      #       - testFrontEnd
-      # - auditBackEnd:
-      #     requires:
-      #       - testBackEnd
-      - deploy-infrastructure
-      # :
-      #     requires: [auditFrontEnd,auditBackEnd]
+      - build-frontend
+      - build-backend
+      - test-frontend:
+          requires: [build-frontend]
+      - test-backend:
+          requires: [build-backend]
+      - scan-backend:
+          requires: [build-backend]
+      - scan-frontend:
+          requires: [build-frontend]
+      - deploy-infrastructure:
+          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
       - configure-infrastructure:
-          requires:
-            - deploy-infrastructure
+          requires: [deploy-infrastructure]
       - run-migrations:
-          requires:
-            - configure-infrastructure
+          requires: [configure-infrastructure]
       - deploy-frontend:
-          requires:
-            - configure-infrastructure
+          requires: [configure-infrastructure]
       - deploy-backend:
-          requires:
-            - configure-infrastructure
+          requires: [configure-infrastructure]
       - smoke-test:
-          requires:
-            - configure-infrastructure
+          requires: [deploy-backend, deploy-frontend]
+      # - cloudfront-update:
+      #     requires: [smoke-test]
+      # - cleanup:
+      #     requires: [cloudfront-update]
